build_from:
  armhf: docker.io/library/alpine:3.23
  armv7: docker.io/library/alpine:3.23
  aarch64: docker.io/library/alpine:3.23
  amd64: docker.io/library/alpine:3.23
  i386: docker.io/library/alpine:3.23
