build_from:
  armhf: docker.io/library/alpine:3.19
  armv7: docker.io/library/alpine:3.19
  aarch64: docker.io/library/alpine:3.19
  amd64: docker.io/library/alpine:3.19
  i386: docker.io/library/alpine:3.19
